JAVAC=/usr/bin/javac
JAVA=/usr/bin/java
.SUFFIXES: .java .class
SRCDIR=src
BINDIR=bin


$(BINDIR)/%.class:$(SRCDIR)/%.java
	$(JAVAC) -d $(BINDIR)/ -cp $(BINDIR) -sourcepath $(SRCDIR) $<

CLASSES= clubSimulation/GridBlock.class clubSimulation/ClubGrid.class  clubSimulation/Clubgoer.class clubSimulation/ClubView.class clubSimulation/CounterDisplay.class\
				 clubSimulation/PeopleCounter.class clubSimulation/PeopleLocation.class clubSimulation/ClubSimulation.class\

CLASS_FILES=$(CLASSES:%.class=$(BINDIR)/%.class)

default:$(CLASS_FILES)

clean:
	rm $(BINDIR)/clubSimulation/*.class

run:$(CLASS_FILES)
	$(JAVA) -cp bin clubSimulation/ClubSimulation

docs:
	javadoc -d doc/ src/*.java
